In [1]:
%pylab inline
from pandas import Series, DataFrame
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


In [6]:
obj = Series([4, 7, -5, 3])
print type(obj.values)
print obj.index

<type 'numpy.ndarray'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [17]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [41]:
frame.ix[1:2,'pop':'state']

pop state
1  1.7  Ohio
2  3.6  Ohio

In [34]:
obj = Series(np.arange(4.),index=['a', 'b', 'c', 'd'])

In [35]:
obj['a':'c']

a    0
b    1
c    2
dtype: float64

In [49]:
ser = Series(np.arange(3.))
ser2 = Series(np.arange(3.), index=['a', 'b', 'c'])
print ser2

a    0
b    1
c    2
dtype: float64


In [61]:
ser.ix[1]

1.0

In [82]:
path="/Users/flashhack/Workspace/Study/Pandas/pydata-book/"
!cat /Users/flashhack/Workspace/Study/Pandas/pydata-book/ch06/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [97]:
df=pd.read_csv(path+"ch06/ex5.csv")
df

something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6 NaN   8   world
2     three  9  10  11  12     foo

In [90]:
df.to_csv(path+"ch06/out.csv")
tmp=path+"ch06/out.csv"
!cat $tmp

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo


In [92]:
df.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo


In [102]:
df.rename(columns={'b':'haha'},inplace=True)
df

something  a  haha   c   d message
0       one  1     2   3   4     NaN
1       two  5     6 NaN   8   world
2     three  9    10  11  12     foo

In [106]:
permutation(range(5,10))

array([9, 7, 6, 5, 8])

In [107]:
df.describe()

a  haha          c   d
count  3     3   2.000000   3
mean   5     6   7.000000   8
std    4     4   5.656854   4
min    1     2   3.000000   4
25%    3     4   5.000000   6
50%    5     6   7.000000   8
75%    7     8   9.000000  10
max    9    10  11.000000  12

In [50]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)
data

array([[ 0.93799262, -0.03346789, -0.35147043,  0.18817909],
       [ 0.32153386,  0.99379685, -0.87253067,  0.33927963],
       [-1.08958941, -1.09183545,  0.477998  , -0.8298043 ],
       [ 0.3494059 ,  0.05932365, -0.63048417, -0.13119998],
       [ 0.51124803, -0.34665714,  0.90050637,  0.61242754],
       [ 0.57610156,  0.56500324,  0.69600503, -0.01767426],
       [-1.30036488, -1.81379924,  0.36738553,  1.29968635]])

In [15]:
mask=names=='Bob'
mask

array([ True, False, False,  True, False, False, False], dtype=bool)

In [32]:
data_tmp=data[mask]
data_tmp

array([[-0.54536057,  0.35904705, -0.71988866, -0.03129625],
       [-0.47801208, -0.5254658 ,  0.50630786, -1.5040682 ]])

In [25]:
data_tmp[:,1]=0

In [39]:
data[mask]=0

In [54]:
data_tmp=data[[2,4,3]]
data_tmp

array([[-1.08958941, -1.09183545,  0.477998  , -0.8298043 ],
       [ 0.51124803, -0.34665714,  0.90050637,  0.61242754],
       [ 0.3494059 ,  0.05932365, -0.63048417, -0.13119998]])

In [55]:
data_tmp=0

In [60]:
data[[2,4,3]][:,:]=0

In [61]:
data

array([[ 0.93799262, -0.03346789, -0.35147043,  0.18817909],
       [ 0.32153386,  0.99379685, -0.87253067,  0.33927963],
       [-1.08958941, -1.09183545,  0.477998  , -0.8298043 ],
       [ 0.3494059 ,  0.05932365, -0.63048417, -0.13119998],
       [ 0.51124803, -0.34665714,  0.90050637,  0.61242754],
       [ 0.57610156,  0.56500324,  0.69600503, -0.01767426],
       [-1.30036488, -1.81379924,  0.36738553,  1.29968635]])

In [56]:
data_tmp

0

In [154]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [183]:
frame

pop   state  year  debt eastern
0  2.5    Ohio  2000   NaN    True
1  2.7    Ohio  2001   NaN    True
2  4.6    Ohio  2002  -1.2    True
3  3.4  Nevada  2001   NaN   False
4  3.9  Nevada  2002  -1.5   False

In [156]:
val = Series([-1.2, -1.5, -1.7],index=[2,4,5])

In [157]:
frame['debt'] = val

In [158]:
frame['eastern'] = frame.state == 'Ohio'

In [104]:
frame_tmp=frame['eastern']

In [106]:
frame_tmp=False

In [107]:
frame_tmp

False

In [70]:
del frame['eastern']

In [150]:
frame.ix[:,2:3]=0

In [185]:
formatter = lambda x : x+10
print formatter(2.5)
#frame['pop'].replace(formatter,inplace=True)
frame['pop'].replace(formatter)

12.5


0    2.5
1    2.7
2    4.6
3    3.4
4    3.9
Name: pop, dtype: float64

#Multi Indexing

In [23]:
data = Series(np.random.randn(10), index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [26]:
data

a  1   -0.194633
   2   -3.448941
   3   -0.726831
b  1    0.177037
   2    1.157958
   3   -0.413805
c  1   -0.009886
   2   -0.867564
d  2   -0.064362
   3   -0.598434
dtype: float64

In [27]:
data.unstack().stack()

a  1   -0.194633
   2   -3.448941
   3   -0.726831
b  1    0.177037
   2    1.157958
   3   -0.413805
c  1   -0.009886
   2   -0.867564
d  2   -0.064362
   3   -0.598434
dtype: float64

In [33]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
'd': [0, 1, 2, 0, 1, 2, 3]})

In [34]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [35]:
frame2=frame.set_index(['c','d'])

In [64]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [63]:
frame2.xs(0,level='d')

a  b
c        
one  0  7
two  3  4

In [67]:
frame3 = DataFrame({'a': range(7), 'b': range(7, 0, -1),
'c': ['two', 'two', 'two', 'three', 'three', 'three', 'three'],
'd': [0, 1, 2, 0, 1, 2, 3]})

In [68]:
frame3 = frame3.set_index(['c','d'])
frame3

a  b
c     d      
two   0  0  7
      1  1  6
      2  2  5
three 0  3  4
      1  4  3
      2  5  2
      3  6  1

In [69]:
frame2.add(frame3,fill_value=0)

a   b
c     d       
one   0  0   7
      1  1   6
      2  2   5
three 0  3   4
      1  4   3
      2  5   2
      3  6   1
two   0  3  11
      1  5   9
      2  7   7
      3  6   1

In [70]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1